### ISSUE TITLE
Client crashing when internet disconnects

### ISSUE THREAD

**Issue by tree786** [lemunozm/message-io#103]
Hello .!

I am currently running into an issue when the internet disconnects on the client side, since the client freezes (crashing) when that happen. The server remains fine (during disconnection) and returns when the internet reconnects, however the client remains in frozen state. Here is a simplified view of my code on client side:

```
fn main() {

    let (node_handler,node_listener)=node::split::<()>();

    let (endpoint,_)=node_handler.network().connect(Transport::Udp,"127.0.0.1").unwrap();

    let (node_task, mut receive)=node_listener.enqueue();

    let mut listener_struct=ListenerStruct{handler:node_handler,receiver:receive,server_endpoint:endpoint};

    let msg=String::from("client"); //send message to server
    listener_struct.handler.network().send(listener_struct.server_endpoint,msg.as_bytes());

    loop{ //game loop
        let msg=String::from("client"); //send message to server
        listener_struct.handler.network().send(listener_struct.server_endpoint,msg.as_bytes());

        match listener_struct.receiver.receive(){
            NodeEvent::Network(event) => match event{
                StoredNetEvent::Connected(_,_)=>{
                    println!("{:?}","connected");
                },
                StoredNetEvent::Accepted(_,_)=>{

                },
                StoredNetEvent::Message(_,data)=>{

                let mut packet=String::from_utf8(data); //receive packet from server

                },
                StoredNetEvent::Disconnected(_)=>(),
                }
                NodeEvent::Signal(sig)=>match sig{
                    ()=>{

                    }
                }
            }
    }
}

```
I not sure why the client crashing, but I thought, maybe there is a way to check the internet status (on client), and then if the status==disconnected, then we temporarily "pause" the client (and wait until connection re-established)? But other than that, is the crashing due to running the `send()` and `receive()` functions inside a loop, which cannot connect/listen to server when the internet connection lost? Is there a way of tempoarilry stopping them if that is the case?

Thanks for helping .!

**Comment by lemunozm** [comment]
Hi @tree786, I can not tested yet your code. But a first view, If the server do not answer your client (for example, because the packet has lost due to the disconnection), the `receive()` method will block your client since there is no packet. If you use the receive part inside the loop, I encourage to use better `try_receive()` (even you could call try_receive()` several times per game step).

**Comment by tree786** [comment]
Hi , Thanks very much, that have solved my issue ! Like you said, it was crashing because the receive was blocking when net disconnect. Many Thanks ! :)
