### ISSUE TITLE
How to dynamic switch discovery-server?

### ISSUE THREAD

**Issue by NateLing** [lemunozm/message-io#104]
New message-io user, thanks for this useful crate. 

I don't know how to dynamic switch discovery-server if it goes down, Is there a way to do it?

Like this:

                        DS1 ---------- DS2
                          /\ 
                         /   \
                       /       \
                     /           \
         participant1 participant2 ...

If DS1 goes down, i want to all the  participants switch to DS2.

**Comment by lemunozm** [comment]
Hi @NateLing 

It depends on how your application works. What is exactly your problem? how to detect the server goes down once it is discovered by UDP multicast? If you discover a server, you after probably connect with the server by:
- **TCP/WebSocket**, so in this case, you should rediscover once the connection goes down (you receive a Disconnected event).
- **UDP**, which you should build in top of it your application protocol able to detect the server is down (maybe with a heartbeat mechanism?), and then rediscover to find the other server.

**Comment by lemunozm** [comment]
In these network topologies, you usually use two sockets, one to discover, and another one to "talk" with the server.
The second one can connect with the server using the information that the first one provides (ip, port, credentials...).

Maybe the confusion comes from this.

**Comment by NateLing** [comment]
Sorry, i forgot this. i should handle the Disconnected event. if the current discovery-server was down, switch participant to the backup discovery-server. thanks.

**Comment by lemunozm** [comment]
I close the issue, feel free to reopen it
