### ISSUE TITLE
cross compile for websocket

### ISSUE THREAD

**Issue by reison1218** [lemunozm/message-io#108]
if i want to use ws,but do not open ssl,how to do it?
em....i mean,cross compile openssl from windows or mac to linux is so troublesome.so maybe there is a way use ws but not use wss?
for now,when i cross compile from mac to linux,it's always occur error,the errors are about openssl,if i  open Ws feature. 
if i mistake something,pls tell me.
by the way,thanks for your work,message-io is great!

**Comment by lemunozm** [comment]
Hi @reison1218,

In fact, the `websocket` feature would enable only the WebSocket, without TLS. I created a new PR https://github.com/lemunozm/message-io/pull/109 with that change and just merged into version `0.14.3`.

I hope it goes well for your use case :)

**Comment by reison1218** [comment]
Hi @lemunozm 
i have try  0.14.3,it's work!
thanks for your work!:)
