### ISSUE TITLE
There is no reactor running

### ISSUE THREAD

**Issue by fgadaleta** [lemunozm/message-io#116]
I am experiencing the error below 
thread '<unnamed>' panicked at 'there is no reactor running, must be called from the context of a Tokio 1.x runtime', 

when I send a message to a `NodeListener` and then spawn a thread in a tokio runtime to process that message.

Is this error familiar to anyone?

**Comment by lemunozm** [comment]
Hi,

Maybe the `NodeListener` callback is not called from the tokio context?

Are you using `for_each` or `for_each_async` to read the messages? The second one uses its own thread internally that will be out of the tokio context.
