### ISSUE TITLE
Modify some parameters of udp connection

### ISSUE THREAD

**Issue by Be33eD** [lemunozm/message-io#130]
Hi,

I noticed that '0.0.0.0:0' is used in the code, which means a random port is assigned. Is there some way I can bind UDP to a specified port?

```rust
fn connect(remote_addr: RemoteAddr) -> io::Result<ConnectionInfo<Self>> {
    let socket = UdpSocket::bind("0.0.0.0:0".parse().unwrap())?;
    let peer_addr = *remote_addr.socket_addr();
    socket.connect(peer_addr)?;
    let local_addr = socket.local_addr()?;
    Ok(ConnectionInfo { remote: RemoteResource { socket }, local_addr, peer_addr })
}
```

Also, can I set some timeout on read/write, for example using set_read_timeout()/set_write_timeout().

**Comment by lemunozm** [comment]
HI @Be33eD, yes it's hardcoded when you perform an output connection. When you listen, you can specify the port. 

This more "advance" configuration, along with the timeout configuration is not supported currently in `message-io`. There is an [open issue](https://github.com/lemunozm/message-io/issues/54) where I wanted to add some configuration transport-related properties at connect/listen calls. In those configurations, you could specify these kinds of things as local port, timeouts, etc. 

Currently, I do not have time to tackle new features on `message-io`, only some bugs/issues. Maybe in a near future. Sorry for the inconvenience. Of course, if any brave person wants to make a PR with this, I will give them all my support.

**Comment by Be33eD** [comment]
Thanks a lot for your reply and work on message-io, it's a really great library.

I will continue to try other ways to solve this problem.
