### ISSUE TITLE
Send message from basic websocket client

### ISSUE THREAD

**Issue by MaximeM** [lemunozm/message-io#133]
Hey there,

I'm quite new to rust, so I implemented the basic server example.

I used Unreal Engine 5 C++ web socket implementation and sucessfully connected to the server.

My problem is when sending message they don't register, I guess it's a format issue?

If you had any clue, your crate is exactly what I should use for my Game Server.

**Comment by MaximeM** [comment]
Fix the format, as regular String won't be processed.

**Comment by lemunozm** [comment]
Hi @MaximeM, currently, Websocket implementation in message-io works for binary data, not for text data. Maybe your issue comes from there.
