### ISSUE TITLE
Disconnecting badly acting client (endpoint)

### ISSUE THREAD

**Issue by PPakalns** [lemunozm/message-io#134]
For connection based protocol like TCP for the server it is not possible to disconnect single endpoint that could be a bad actor.

`node::NodeHandler.network().remove(resource_id)` only supports removing all endpoints.

P.S. This is a very good library, thank you for developing it.

**Comment by lemunozm** [comment]
Hi @PPakalns, thanks for your nice words 😃 

Regarding the issue, I think you are using the `resource_id` from the TCP listener.
When you accept a connection by TCP, it returns an endpoint that contains the `resource_id` of that isolated connection. That's the resource id you need to remove.

**Comment by PPakalns** [comment]
Tried out, you are right. Thanks for the support.
