### ISSUE TITLE
Release v0.15.0

### ISSUE THREAD

**Issue by lemunozm** [lemunozm/message-io#142]
Changes:
- #141
- #145
- #146 
- #148
- #149
- #143
- [x] Update `Cargo.toml` version 
- [x] Update changelog
- [ ] Upload release and tag it

**Comment by kgraefe** [comment]
When #141 is merged, I would like to add options for
- TCP keepalive settings and
- specifying UDP source address for outgoing packets (basically #130  )

**Comment by lemunozm** [comment]
That would be great! 🥳

**Comment by lemunozm** [comment]
I think it's ready to deliver the release.

Do you have any other PR in mind @kgraefe that you want to add to this release?

**Comment by kgraefe** [comment]
nope, thanks for asking

**Comment by kgraefe** [comment]
or maybe hold on... I have one more which I'm not sure you want to merge because it's a bit of code for our special case and it's Linux only. But maybe I should open a PR so you can decide?

**Comment by lemunozm** [comment]
If ready, I can make the release

**Comment by kgraefe** [comment]
yes please :-) thank you for creating and maintaining this library

**Comment by lemunozm** [comment]
Thank You for making it better! 🤗
