### ISSUE TITLE
Not compiling on linux (ubuntu 22.04)

### ISSUE THREAD

**Issue by Zorz42** [lemunozm/message-io#164]
It does not compile on linux. It only compiles on MacOS and Windows. This is the error I get:

<img width="1366" alt="Screenshot 2023-09-10 at 6 17 40 PM" src="https://github.com/lemunozm/message-io/assets/54270248/99b07e89-9263-4848-91fa-b0eee11b40ec">

I have the latest toolchain and everything is up to date. Tried it on 2 different machines, same result.

**Comment by Zorz42** [comment]
Nevermind, its already a pull request

**Comment by lemunozm** [comment]
Yeah, for traceability: https://github.com/lemunozm/message-io/pull/163
