### ISSUE TITLE
How to parse binary message data in other language?

### ISSUE THREAD

**Issue by sanjitako** [lemunozm/message-io#19]
i'm trying to build an Android App and use message-io for my message service , but there is a big problem that how to parse binary message in java/kotlin ?

**Comment by lemunozm** [comment]
Hi @sanjitako, 

I do not know if you are using rust in your backend that communicates with your Android App or you are using it as a library in your Android App.

If it is the first case:
At this time, you need to have message-io in all the endpoints to manipulate the messages. Parse the message consist of two phases: decoding and deserializing, and there is no trivial way to do it without the library.
I want to give support for WebSocket, which uses its own encoding and will facilitate interoperability with other languages/technologies

If it is the second case: 
I suppose that you are using an upper layer in Java/Kotlin and a lower layer in rust which uses message-io. You need to transform the already parsed rust struct in rust to your java/Kotlin object. The decoding/serialization phase must be done at the rust level by message-io.

Have I been able to help you?

**Comment by sanjitako** [comment]
Very helpful! Thanks!
i think second way is better and i will try to write a layer to parse message.
