### ISSUE TITLE
Bump-up crossbeam-channel

### ISSUE THREAD

**Issue by djKooks** [lemunozm/message-io#20]
Hello~
I'm looking up the project currently, and have a question.

Seems it is using `crossbeam-channel`, but seems it has been moved to `crossbeam`, with 0.8 version.
Is there plan to bump-up?

**Comment by lemunozm** [comment]
Hi @djKooks,

The idea is to maintain the third parties to the last version. Thanks for noticing it. I will update `crossbeam` in the next versión of the library. 

Also, if you want, you can make a PR with this change.

**Comment by djKooks** [comment]
@lemunozm thanks for help~
Just curiosity, do you have some plan/roadmap in mind, for the project?

**Comment by lemunozm** [comment]
> @lemunozm thanks for help~
> Just curiosity, do you have some plan/roadmap in mind, for the project?

Yes! I am currently working on making some internal refactorizations to allowing the integration of new transports easily. Once I finished it (version 0.6), the first ones I want to add are WebSockets and [laminar](https://github.com/amethyst/laminar) (understanding it as a "transport layer"). 

The idea is to keep the internal architecture the cleanest possible to allow people to contribute with other transports easily.

Also, I have in mind other improvements as allow custom serializations.
