### ISSUE TITLE
Encryption

### ISSUE THREAD

**Issue by tarcieri** [lemunozm/message-io#26]
Are you planning on adding encrypted connections at some point?

**Comment by lemunozm** [comment]
Hi @tarcieri, the idea is to add the new adapters as *WebSocket* (currently working), *webRTS* and *TLS* (I think that you are asking for something like this one).

If you (or someone) are interested in other protocols/transports, it can be implemented easily as I mention [here](https://github.com/lemunozm/message-io#do-you-need-a-transport-protocol-that-message-io-doesnt-have-add-it-).

**Comment by lemunozm** [comment]
Regardin security, now `message-io` supports *secure Websockets* using the schema `wss://domain:port/...` at connection

**Comment by tarcieri** [comment]
Cool, I think this can be closed then
