### ISSUE TITLE
Sendin big data, or multiple small data is not working correctly

### ISSUE THREAD

**Issue by sigmaSd** [lemunozm/message-io#3]
original discussion https://github.com/lemunozm/termchat/pull/11

Sending multiple small data:
 - using this branch https://github.com/sigmaSd/termchat/tree/send_in_chunks (sends file in small chunks)
 - send a 10mb file with ?send
 - try to send any message after -> no message is received
 - debugging this lead me to encoding here https://github.com/lemunozm/message-io/blob/master/src/encoding.rs#L100 decoded_data at some point becomes always None

Sending big data:
   - using this branch  https://github.com/sigmaSd/termchat/tree/send_files (send the whole file in one send)
   - send 10mb file
   - receiver will crash here https://github.com/lemunozm/message-io/blob/master/src/network.rs#L112 ``Err value: Io(Kind(UnexpectedEof))
   - the issue might be here https://github.com/lemunozm/message-io/blob/master/src/encoding.rs#L11 the PADDING can be too small for the data length

**Comment by lemunozm** [comment]
Thanks to collect all the info. I will fix it asap :)

**Comment by lemunozm** [comment]
> * using this branch [sigmaSd/message-io@df4c5c8](https://github.com/sigmaSd/message-io/commit/df4c5c8) (sends file in small chunks)

I have no access to this commit :S

**Comment by sigmaSd** [comment]
https://github.com/sigmaSd/termchat/tree/send_in_chunks

**Comment by sigmaSd** [comment]
Yep wrong link, now its the correct one

**Comment by lemunozm** [comment]
Did you test it with two different physical computers or two instances on the same computer?

**Comment by sigmaSd** [comment]
All tests Ive done are on the same machine with different user names

**Comment by lemunozm** [comment]
The PR https://github.com/lemunozm/message-io/pull/4 fix this issue

**Comment by sigmaSd** [comment]
I tested and looks like both issues are fixed!

**Comment by sigmaSd** [comment]
The second issue is fixed, the first one is still reproducible, I'll try to post the steps to reproduce.

**Comment by sigmaSd** [comment]
I had an issue with testing (I kept old instances of termchat active).

Everything appears to be ok with the new changes!

**Comment by lemunozm** [comment]
Glad to hear good news!

I close the issue then 😄
