### ISSUE TITLE
MacOS issue with some unitary tests

### ISSUE THREAD

**Issue by lemunozm** [lemunozm/message-io#6]
Some UTs in [`src/events.rs`](src/events.rs) related to the timers fails only in macOS builds (see https://github.com/lemunozm/message-io/runs/1339555571?check_suite_focus=true). The issue is non-deterministic. 

Unfortunately, I have no Mac to debug it :(

**Comment by sigmaSd** [comment]
@lemunozm you can try https://github.com/fastai/fastmac

**Comment by sigmaSd** [comment]
Those 2 tests also fail on linux. But the failure ratio is small, a run fail in 10/20 runs.

**Comment by lemunozm** [comment]
Thanks! It should be a time issue because in my local Linux those tests never fail. Should be big delays in the Github CI machines. I will check the reason, maybe a higher threshold is the solution.

**Comment by lemunozm** [comment]
Closed in: https://github.com/lemunozm/message-io/pull/7
