### ISSUE TITLE
Way to manually poll instead of 'for_each'

### ISSUE THREAD

**Issue by tree786** [lemunozm/message-io#88]
Hallo

I have been trying to integrate the message-io in a game framework i am currently using. However , I have been experiencing blocking issues which I am not sure how to overcome (i am very to this). To explain: I have setup a simple Tcp server by following the [server example ](https://github.com/lemunozm/message-io#all-in-one-tcp-udp-and-websocket-echo-server)which works well. However, I have setup the client in a different fashion, by integrating it ([client example](https://github.com/lemunozm/message-io#echo-client)) into the game loop , which can run at 60fps. This is causing my game to freeze, and i think is because it runs an infinite loop (since client runs `listener.for_each` loop, which is itself inside the game loop). Of course i am quite new to this, but I was wondering; is there a way to manually poll, instead of using the `for_each` method? That way I could integrate the client exmaple directly in the game loop and not worry about blocking issues.  I have attached source file below, just run `cargo run --release` on server to open server, then `cargo run --release` on client (and notice how game window freezes to white)
Hope i explained well.. Thanks!

[integration issue.zip](https://github.com/lemunozm/message-io/files/6566396/integration.issue.zip)

**Comment by lemunozm** [comment]
Hi @tree786,

Yeah, `listener.for_each()` will run forever (until you call `NodeHandler::stop()`), and it will block your game loop if you call from inside.

To use the `NodeListener` with a game loop you can use several patterns:

### 1. Shared state
```rust
let game_state: Arc<Mutex<GameState>> = Arc::new(Mutex::new(GameState::new()));

let task = listener.for_each_async(|event| { //The async version will not block
    //deserialize
    //modify the game state
});

loop {
    let state = game_state.lock().unwrap();
    // Your game logic
    //...

    // unlock state
    // wait for the next frame (in the meantime, the for_each function can access the state to update it)
}
```

### 2. Sending actions
```rust
let (sender, recevier) = mpsc::channel();
let task = listener.for_each_async(|event| { //The async version will not block
    //deserialize
    //idenfity the action
    sender.send(action):
});

let game_state = GameState::new();

loop {
    for action in receiver.try_iter() { // Do not block if try_iter is used
         //Do the network logic for each action
    }

    // Your game logic
    //...
}
```

### 3. Use [`listener.enqueue()`](https://docs.rs/message-io/0.14.0/message_io/node/struct.NodeListener.html#method.enqueue)
The easier way but it could reduce slightly the performance because it copies the message.

```rust
let game_state = GameState::new();
let (task, mut receiver) = listener.enqueue();

loop {
    for node_event in receiver.try_receive() { // Do not block if try_receive() is used
         //Deserialize the message here
         //Do the network logic for this message/event
    }

    // Your game logic
    //...
}
```

I hope it helps you!

**Comment by tree786** [comment]
Hi, Thanks very much for detailed answer! I have attempted to try point (3), however I still seem to be having infinite loop issues (i.e. freezing game) , due to my limited info on integrations. What I want to do is call the `listener.enqueue()` function once every frame (i.e. manually have control over execution rate), rather than allowing it to run infinitely in the game . Thanks and apoligyes for bothering you with this!

**Comment by lemunozm** [comment]
Hi @tree786,

The `listener.enqueue()` takes ownership of the `NodeListener` to transform it into an event queue. It must be called only once. The `NodeListener::enqueue()` will return an [`EventReceiver`](https://docs.rs/message-io/0.14.0/message_io/events/struct.EventReceiver.html) that is the receiver part of the event queue that can be used every frame in order to receive the events (it contains typical channel methods as `receive()`, `receive_timeout()`, `try_receive()`.

Since the `listener.enqueue()` will make the node send asynchronously events into the `EventReceiver` it must be alive during that process. To achieve this, you need to assign the `NodeTask` entity to an variable to not drop it:

```rust
fn my_game() {
    let (task, mut receiver) = listener.enqueue();

    loop {
        // Use the receiver here (the task must live during that process, if not, no event will be received.
    }
    // task is dropped here. You could save it into a struct with a higher lifetime than the function scope 
    // if you need the node "alive".
}
```

**Comment by tree786** [comment]
Hi , thanks very much again for detailed answer ! I think this is good, it works well however I am running into some issues when integrating it in the game framework I using. I think issue is due to the game framework, so I need to investigate that. But thanks again , I close this issue now!

**Comment by tree786** [comment]
I now working in the game framework. I will soon hopefully post video to show it in a basic 3D cars game multiplayer  intend to make with !

**Comment by lemunozm** [comment]
Cool! If you want, when you have it you can make a PR to add it in the [open source projects](https://github.com/lemunozm/message-io#open-source-projects-using-message-io-) section.

**Comment by tree786** [comment]
Sure that sounds great! :)

**Comment by tree786** [comment]
And just to show the basic progress so far, it is now working very well with the game framework, [video here](https://github.com/tree786/test/blob/main/netw.m4v). This should be the basis for the networked car game I plan to work on shortly!

**Comment by tree786** [comment]
Hello
Apologies if this bad place to post, but not sure where else I should..
As a simple follow up to my posts above ,  I have kind of made the game where any number of clients can connect to server and ride a car.. [Here is video](https://github.com/tree786/test/raw/main/simple%20networked.m4v)
It uses the message-io for networking (mostly UDP, and tiny bit of TCP). There are many issues and problems to solve, and some I think i cannot do due to my lack of underastanding of networking etc
Thanks..

**Comment by lemunozm** [comment]
Sorry, I didn't answer that message. The video is so cool! Go it! 

If you have a problem understanding some message-io concept, do not hesitate to open an issue :)

**Comment by tree786** [comment]
No problems  thanks for comment ! :) I have made a new thread here [link](https://github.com/lowenware/dotrix/discussions/79 ) where i post some update
