### ISSUE TITLE
Net2 is deprecated.

### ISSUE THREAD

**Issue by iMplode-nZ** [lemunozm/message-io#96]
See https://crates.io/crates/net2. It might make sense to switch to socket2.

**Comment by lemunozm** [comment]
Thanks! 

In fact, I have a pending change in https://github.com/lemunozm/message-io/issues/70 that implies making exactly the change you suggest.

**Comment by lemunozm** [comment]
Fixed in https://github.com/lemunozm/message-io/issues/70
