### ISSUE TITLE
Compiling message-io with just `websocket` feature breaks.

### ISSUE THREAD

**Issue by iMplode-nZ** [lemunozm/message-io#98]
Error message:
```
error[E0433]: failed to resolve: could not find `tcp` in `super`
   --> /home/redact/.cargo/registry/src/github.com-1ecc6299db9ec823/message-io-0.14.1/src/adapters/ws.rs:183:45
    |
183 |                     let tcp_status = super::tcp::check_stream_ready(&stream.0);
    |                                             ^^^ could not find `tcp` in `super`
```
This might be intended, but in that case there should be `websocket = ["tcp"]`. It also doesn't make sense for the web either. Maybe have two different `websocket` features? `websocket` and `websocket-web`.

**Comment by lemunozm** [comment]
Ouch! This is due to a recent refactorization. I will fix it ASAP!

Thanks!!

**Comment by lemunozm** [comment]
As you suggested, this https://github.com/lemunozm/message-io/pull/99 fixes the compilation issue.

Regarding your comment, why you say that this change doesn't make sense for the web? Maybe i'm not understanding something

**Comment by iMplode-nZ** [comment]
Websocket seemed to be an implementation of websocket not bindings to web_sys's websocket?

**Comment by lemunozm** [comment]
Sorry, I didn't understand you well. Yes, the message-io implementation is based in [tungstenite-rs](https://github.com/snapview/tungstenite-rs). which seems to not support wasm.

The idea will be to detect the current platform and swap the WebSocket adapter implementation from tungstenite to some other crate as `web-sys` or `ws_stream_wasm`. At this moment you can not use WebSocket with wasm. Sorry for the inconvenience. I will create a new issue to tackle this feature.

**Comment by lemunozm** [comment]
I close this issue (since the compilation problem is solved) and open https://github.com/lemunozm/message-io/issues/100 instead to tracking the wasm support
